### ISSUE TITLE
CDN includes

### ISSUE THREAD

**Issue by notenociz** [eduardo-costa/shortcutcss#3]
Would it be beneficial to include shortcutcss additionally via a CDN? This means that it could be used faster and would take off any pressure on the user to add it additionally and thus they could use it for rapid prototyping and then rewrite with actual components and any utilities that must be there. The reason that they shouldn't use utility classes fully is outlined [here](http://csswizardry.com/2015/03/can-css-be-too-modular/) by @csswizardry.

**Comment by eduardo-costa** [comment]
Do you suggest any free CDN service?

I agree with the points about atomic CSS.
The main difference with shortcutcss is that I'm using a more explicit naming convention.
So `rel` is `relative`, `abs` is `absolute` and so on.
Also I don't want to substitute a more advanced class like `.button` by several pieces that would make the button.
I would do:

``` sass
.button
{
  position: relative;
  display: inline-block;
  border-radius: 3px;
  background-color: #f00; //default color
  color: #fff; //default color
}
```

then if needed override some attribs.

``` html
<a class="button"></a>
<!-- yellow text / blue background / absolute-->
<a class="button t-yellow bk-blue abs"></a>
```

also sometimes I'll do

``` html
<section class="main">
  <!-- 'tc' can be changed by 'tl' or 'tr' better than editing content -->
  <div class="content tc">
    <!-- dummy div just to make 'A' 'B' 'C' conform to content's 'tc' 'tl' or 'tr' -->
    <div class="ib">
      <span>A</span>
      <span>B</span>
      <span>C</span>
    </div>
  </div>
</section>
```

**Comment by notenociz** [comment]
[Cloudflare](https://www.cloudflare.com/) is probably best for now

**Comment by eduardo-costa** [comment]
Will add a request at `cdnjs`

**Comment by eduardo-costa** [comment]
Created the CDN links my self.
Updated in the README

**Comment by notenociz** [comment]
Thanks for that

**Comment by eduardo-costa** [comment]
If you work with FrontEnd HTML+JS
Take a look at this MVC framework I did!
https://github.com/eduardo-costa/frontjs
